### ISSUE TITLE
startup fails

### ISSUE THREAD

**Issue by scherler** [awamper/draobpilc#1]
Hi I just installed via git:

'''
root@bulldozer:/opt/n# pip3 install git+https://github.com/awamper/draobpilc
'''

Then I want to start with:

'''
bulldozer% draobpilc
Traceback (most recent call last):
  File "/usr/local/bin/draobpilc", line 9, in <module>
    load_entry_point('Draobpilc==0.1', 'gui_scripts', 'draobpilc')()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/main.py", line 139, in run
    app = Application()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/application.py", line 69, in __init__
    self._history_items = HistoryItems()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/history_items.py", line 35, in __init__
    self.reload_history()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/history_items.py", line 109, in reload_history
    self._raw_history = gpaste_client.get_raw_history()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/lib/gpaste_client.py", line 72, in get_raw_history
    return _client.GetRawHistory()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gnome.GPaste1' on object at path /org/gnome/GPaste
'''

How can I use the extension?

**Comment by awamper** [comment]
It looks like you don't have GPaste running/installed.
try
> gpaste dr

and if it doesn't work install GPaste

**Comment by awamper** [comment]
Did it help?

**Comment by scherler** [comment]
Sorry, for coming back so late on that. No it did not:

'''
◎ gpaste dr                                                                                 5.7G ~cbb master 17:29:07
Successfully reexecuted the daemon
◎ draobpilc                                                                                 4.7G ~cbb master 18:19:08
Traceback (most recent call last):
  File "/usr/local/bin/draobpilc", line 9, in <module>
    load_entry_point('Draobpilc==0.1', 'gui_scripts', 'draobpilc')()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/main.py", line 139, in run
    app = Application()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/application.py", line 69, in __init__
    self._history_items = HistoryItems()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/history_items.py", line 35, in __init__
    self.reload_history()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/history_items.py", line 109, in reload_history
    self._raw_history = gpaste_client.get_raw_history()
  File "/usr/local/lib/python3.4/dist-packages/draobpilc/lib/gpaste_client.py", line 72, in get_raw_history
    return _client.GetRawHistory()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gnome.GPaste1' on object at path /org/gnome/GPaste
'''

**Comment by awamper** [comment]
What version of gpaste do you have?

**Comment by scherler** [comment]
GPaste 3.14

**Comment by awamper** [comment]
GPaste 3.18+ required.

**Comment by scherler** [comment]
ok will try that from home
