### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by usnmustanger** [awamper/draobpilc#21]
I installed via PIP3 on Ubuntu 19.10. I get the following error when I run the draobpilc command. What am I missing?

> ~$ draobpilc
> /home/<user>/.local/lib/python3.7/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
>   from gi.repository import Notify
> Traceback (most recent call last):
>   File "/home/<user>/.local/bin/draobpilc", line 10, in <module>
>     sys.exit(run())
>   File "/home/<user>/.local/lib/python3.7/site-packages/draobpilc/main.py", line 145, in run
>     from draobpilc.application import Application
>   File "/home/<user>/.local/lib/python3.7/site-packages/draobpilc/application.py", line 47, in <module>
>     from draobpilc.widgets.preferences import show_preferences
>   File "/home/<user>/.local/lib/python3.7/site-packages/draobpilc/widgets/preferences.py", line 24, in <module>
>     from gi.repository import GPaste
>   File "/usr/lib/python3/dist-packages/gi/importer.py", line 133, in load_module
>     'introspection typelib not found' % namespace)
> ImportError: cannot import name GPaste, introspection typelib not found

TIA!

**Comment by usnmustanger** [comment]
NM. My mistake. I thought gir1.2-gpaste-*.0 was already installed, turns out it wasn't. Installing this package fixed my error.
Closing this.
