### ISSUE TITLE
Startup exception

### ISSUE THREAD

**Issue by hari-rangarajan** [awamper/draobpilc#9]
/home/hari/.local/lib/python3.5/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hari/.local/bin/draobpilc", line 9, in <module>
    load_entry_point('Draobpilc==0.2', 'gui_scripts', 'draobpilc')()
  File "/home/hari/.local/lib/python3.5/site-packages/draobpilc/main.py", line 145, in run
    from draobpilc.application import Application
  File "/home/hari/.local/lib/python3.5/site-packages/draobpilc/application.py", line 47, in <module>
    from draobpilc.widgets.preferences import show_preferences
  File "/home/hari/.local/lib/python3.5/site-packages/draobpilc/widgets/preferences.py", line 24, in <module>
    from gi.repository import GPaste
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GPaste, introspection typelib not found

**Comment by awamper** [comment]
Seems like you don't have GPaste installed.

**Comment by mcepl** [comment]
@awamper well, but shouldn't draobplic require it? Same goes for Python modules ``dbus``, ``xlib``, and ``gobject``, which are required de facto, but not in ``setup.py``, so draobpic fails to work even though pip install ends without a warning.

**Comment by iPublicis** [comment]
I've GPaste installed and also got an error:

```
$ draobpilc --install-desktop-file
/usr/local/lib/python3.7/dist-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "/usr/local/bin/draobpilc", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/draobpilc/main.py", line 145, in run
    from draobpilc.application import Application
  File "/usr/local/lib/python3.7/dist-packages/draobpilc/application.py", line 47, in <module>
    from draobpilc.widgets.preferences import show_preferences
  File "/usr/local/lib/python3.7/dist-packages/draobpilc/widgets/preferences.py", line 24, in <module>
    from gi.repository import GPaste
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GPaste, introspection typelib not found
```

Ubuntu 19.10

**Comment by awamper** [comment]
You need to have gpaste-libs (or whatever its called on ubuntu) installed too.

**Comment by yuriw** [comment]
@hari-rangarajan this is similar to my issue #22 
How did you resolve it ?

**Comment by iPublicis** [comment]
> @hari-rangarajan this is similar to my issue #22
> How did you resolve it ?

Removed it and changed to the Clipboard Indicator extension. No GPaste. No fuss.

https://extensions.gnome.org/extension/779/clipboard-indicator/

**Comment by leisurelyrcxf** [comment]
Fixed by using `apt install libgpaste-dev`
